---
galaxy_info:
  role_name: mlflow_setup
  author: Red Hat Ansible
  description: Configure MLflow tracking server and model registry on Databricks
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: [8, 9]
  galaxy_tags: [databricks, cloud, mlflow, ml, model]
dependencies: []
